### Kode Terakhir Yang Benar
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data

```{r}
library(ggplot2)
library(randomForest)
library(caret)
library(keras)
library(xgboost)
```

## Load Data 

```{r}
# Load the training dataset
training <- read.csv("training.csv") 
```

 
## Basic Preprocessing

```{r}
# Basic Preprocessing: Remove rows with missing values
training <- na.omit(training)

# Menghapus baris dengan nilai string kosong pada kolom 'area'
# training <- training[training$area != "", ]

# Menghapus baris dengan nilai string kosong pada kolom 'market'
# training <- training[training$market != "", ]

hilang_area <- which(training$area=="")
training$area[hilang_area]<-paste0("area ",sample(0:9, length(hilang_area),replace = TRUE))

hilang_market <- which(training$market=="")
training$market[hilang_market]<-paste0("area ",sample(c("L","K"), length(hilang_market),replace = TRUE))
# Split the data into training and testing sets
set.seed(123)  # Set seed for reproducibility
split_ratio <- 0.9  # 90% training, 20% testing
num_rows <- nrow(training)
train_indices <- sample(1:num_rows, size = round(split_ratio * num_rows))
train_data <- training[train_indices, ]
test_data <- training[-train_indices, ]

```

## Training and Evaluating Model

```{r}
# Hyperparameter Tuning using Cross-Validation
# Use caret package for easier hyperparameter tuning
# Adjust parameters as needed based on your dataset and goals
tune_grid <- expand.grid(ntree = c(500, 1000, 1500),
                         mtry = c(2, 5, 10))

# Training the linear regression model using all predictors (Y ~ .)
rf_model <- randomForest(Y ~ ., data = train_data, ntree=5000)
```

```{r}
# Make predictions on the test set
predictions <- predict(rf_model, newdata = test_data)

# Evaluate the model using Mean Squared Error (MSE)
mse <- mean((predictions - test_data$Y)^2)
print(paste("Mean Squared Error:", mse))
```

### Kaggle Subsmission

```{r}
# Load the Kaggle testing dataset
kaggle.test  <- read.csv("testing.csv") 

# Make predictions on the Kaggle testing set
kaggle.test.predictions <- predict(rf_model, newdata = kaggle.test)

# Create a submission data frame with 'index' and 'Y' columns
submission <- cbind(kaggle.test$index, kaggle.test.predictions)
colnames(submission) <- c("index", "Y")

# Generate a unique filename based on the current timestamp
filename = paste("submission",format(Sys.time(), "%Y%m%d%H%M%S"),".csv", sep="")

# Save the submission data frame to a CSV file
write.csv(submission, filename, row.names = FALSE)
```